name: Tag and close stale PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: {}
    
jobs:
  check-stale:
    if: github.repository_owner == 'unitaryfund'
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v6
        with:
          days-before-stale: 120
          days-before-close: 14
          stale-issue-message: This issue had no activity for **4 months**, and will be closed in **2 weeks** unless there is new activity. Cheers!
          stale-issue-label: stale
          stale-pr-message: This pull request had no activity for **4 months**, and will be closed in **2 weeks** unless there is new activity. Cheers!
          stale-pr-label: stale
          exempt-issue-labels: 'bug,roadmap,priority/p0'
          exempt-pr-labels: 'bug,roadmap,priority/p0'
