name: Tag and close stale PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: {}
    
jobs:
  check-stale:
    if: github.repository_owner == 'unitaryfund'
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v3.0.19
        with:
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: This issue had no activity for **2 months**, and will be closed in **one week** unless there is new activity. Cheers!
          stale-issue-label: stale
          exempt-issue-labels: priority/p0,priority/p1,priority/p2
          stale-pr-message: This pull request had no activity for **2 months**, and will be closed in **one week** unless there is new activity. Cheers!
          stale-pr-label: stale
          exempt-pr-labels: priority/p0,priority/p1,priority/p2
