on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+' # Push events to matching sematic versioning, i.e. v1.0, v20.15.10

jobs:
  #generate_artifacts:
  # TODO: make docs pdf and tarball
  create_release:
    if: github.repository_owner == 'unitaryfund'
    runs-on: ubuntu-latest
    steps:
      - name: Check out Mitiq
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: true
          prerelease: false
